"""GPT-OSS 20B Modal deployment for LLM-assisted misconception scoring.

Key decisions and conventions
-----------------------------
- Hosting: deploy with `modal deploy kaggle_map.llm.api`; the module registers a FastAPI POST
  endpoint (`/completions`) on Modal, backed by the GPT-OSS 20B Q2_K_L GGUF weights.
- Bundling: the Modal image bakes the repository into the container via `add_local_dir` and mounts
  a persistent volume at `/root/kaggle-map/models` for downloaded weights.
- Scaling: `ModalDeploymentConfig` exposes `min_containers`/`max_containers`; defaults keep one
  worker warm, with `(0, 3)` recommended for cost-sensitive runs or `(1, 3)` when low latency
  matters. The Makefile passes overrides via `MODAL_MIN_CONTAINERS`/`MODAL_MAX_CONTAINERS` when
  calling `modal deploy`.
- Interfaces: this module exposes a single Modal web endpoint; invoke via HTTP or from other Modal
  apps, not a local CLI.
- API contract: the POST body is `{"prompt": "..."}` and the response shape is
  `{"completion": "..."}`.

Quick reference
---------------
1. Deploy from Makefile
       make deploy-llm
2. Remote curl smoke test (replace `YOUR_URL` with Modal output)
       curl -X POST "https://YOUR_URL/completions" \
           -H "Content-Type: application/json" \
           -d "{\"prompt\": \"Give me three fraction misconceptions\"}"
"""

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import modal
from llama_cpp import Llama
from loguru import logger
from pydantic import BaseModel, Field, computed_field, field_validator, model_validator

from kaggle_map.utils.gguf_model import (
    GGUFModelInferenceConfig,
    GGUFModelName,
    GGUFModelQuantizationLevel,
    format_chat_prompt,
    get_model_path,
    load_llm_model,
)
from kaggle_map.utils.logger_config import configure_logger

configure_logger(__name__)


class PromptRequest(BaseModel):
    prompt: str = Field(..., description="User prompt for GPT-OSS 20B inference.")

    @field_validator("prompt")
    @classmethod
    def strip_and_validate(cls, value: str) -> str:
        stripped = value.strip()
        assert stripped, "Prompt must contain non-whitespace characters."
        return stripped


class CompletionResponse(BaseModel):
    completion: str = Field(..., description="Text generated by the model.")

    @field_validator("completion")
    @classmethod
    def ensure_not_blank(cls, value: str) -> str:
        stripped = value.strip()
        assert stripped, "Completion must not be empty."
        return stripped


class ModalDeploymentConfig(BaseModel):
    app_name: str = Field(default="kaggle-map-gpt-oss")
    volume_name: str = Field(default="kaggle-map-gpt-oss-gguf-cache")
    container_root: Path = Field(default=Path("/root/kaggle-map"))
    min_containers: int = Field(default=1)
    max_containers: int = Field(default=8)
    model_name: GGUFModelName = Field(default=GGUFModelName.GPT_OSS_20B)
    quantization: GGUFModelQuantizationLevel = Field(default=GGUFModelQuantizationLevel.Q2_K_L)

    @model_validator(mode="after")
    def validate_paths(self) -> "ModalDeploymentConfig":
        assert self.container_root.is_absolute(), "Container root must be absolute."
        assert self.min_containers >= 0, "min_containers must be non-negative."
        assert self.max_containers >= 1, "max_containers must be at least one."
        assert self.min_containers <= self.max_containers, "min_containers cannot exceed max_containers."
        return self

    @computed_field
    @property
    def container_weights_path(self) -> Path:
        relative_path = get_model_path(self.model_name, self.quantization)
        return (self.container_root / relative_path).resolve()

    @classmethod
    def default(cls) -> "ModalDeploymentConfig":
        overrides: dict[str, Any] = {}
        min_override = int(os.environ.get("MODAL_MIN_CONTAINERS", "1"))
        max_override = int(os.environ.get("MODAL_MAX_CONTAINERS", "8"))
        if min_override is not None:
            overrides["min_containers"] = min_override
        if max_override is not None:
            overrides["max_containers"] = max_override
        return cls(**overrides)


DEPLOYMENT_CONFIG = ModalDeploymentConfig.default()


@dataclass(slots=True)
class InferenceArtifacts:
    llm: Llama
    inference_config: GGUFModelInferenceConfig


app = modal.App(name=DEPLOYMENT_CONFIG.app_name)

image = (
    modal.Image.debian_slim()
    .apt_install("curl", "git")
    .pip_install(
        "llama-cpp-python>=0.2.90",
        "huggingface-hub>=0.20.0",
        "numpy>=2.0.0",
        "loguru>=0.7.0",
        "pydantic>=2.5.0",
        "rich>=13.0.0",
    )
    .add_local_dir(
        local_path=".",
        remote_path=DEPLOYMENT_CONFIG.container_root.as_posix(),
        copy=True,
        ignore=[".git", "__pycache__", "logs", "datasets", "models"],
    )
)

model_volume = modal.Volume.from_name(DEPLOYMENT_CONFIG.volume_name, create_if_missing=True)
volume_mount_path = (DEPLOYMENT_CONFIG.container_root / "models").as_posix()


def _build_inference_artifacts(config: ModalDeploymentConfig) -> InferenceArtifacts:
    logger.info("Loading GGUF model %s with quantization %s", config.model_name.value, config.quantization.value)
    inference_config = GGUFModelInferenceConfig.get_default_config(config.model_name)
    llm = load_llm_model(config.model_name)
    return InferenceArtifacts(llm=llm, inference_config=inference_config)


def _generate_from_model(
    *,
    llm: Llama,
    inference_config: GGUFModelInferenceConfig,
    model_name: GGUFModelName,
    prompt: str,
) -> str:
    formatted_prompt = format_chat_prompt(model_name, prompt)
    logger.debug("Prompt length after formatting: %d", len(formatted_prompt))
    response = llm.create_completion(
        prompt=formatted_prompt,
        temperature=inference_config.temperature,
        top_p=inference_config.top_p,
        max_tokens=inference_config.max_tokens,
        stop=inference_config.stop_words,
        repeat_penalty=inference_config.repeat_penalty,
    )
    choices = response.get("choices")  # type: ignore[arg-type]
    assert choices, "LLM completion returned no choices."
    first_choice = choices[0]
    text = str(first_choice.get("text", "")).strip()
    if not text:
        message = first_choice.get("message")
        if isinstance(message, dict):
            text = str(message.get("content", "")).strip()
    assert text, "LLM completion was empty."
    logger.debug("Generated completion length: %d", len(text))
    return text


@app.cls(
    image=image,
    gpu="T4",
    min_containers=DEPLOYMENT_CONFIG.min_containers,
    max_containers=DEPLOYMENT_CONFIG.max_containers,
    volumes={volume_mount_path: model_volume},
)
class GPTOSSService:
    @modal.enter()
    def enter(self) -> None:
        logger.info("Warming GPT-OSS 20B worker")
        self._artifacts = _build_inference_artifacts(DEPLOYMENT_CONFIG)
        logger.success("GPT-OSS 20B ready for requests")

    @modal.fastapi_endpoint(method="POST")
    def completions(self, request: dict[str, Any]) -> dict[str, str]:
        prompt = PromptRequest.model_validate(request).prompt
        artifacts: InferenceArtifacts | None = getattr(self, "_artifacts", None)
        assert artifacts is not None, "Inference artifacts missing."
        completion = _generate_from_model(
            llm=artifacts.llm,
            inference_config=artifacts.inference_config,
            model_name=DEPLOYMENT_CONFIG.model_name,
            prompt=prompt,
        )
        return CompletionResponse(completion=completion).model_dump()
